name: github pages build and deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm build
      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: ls -al
      
