name: github pages
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      
      
      - name: push to pages branch
      - run: |
          git config --global user.name "${{ env.USER_NAME }}"
          git config --global user.email "${{ env.EMAIL }}"
          git commit -m -a "new version deploy"
          git push origin gh-pages
      
